version: "3.9"
services:
  web:
    image: node:17
    working_dir: /app
    command: bash -c "npm install && node server-with-wait.js"
    volumes:
      - "build:/app"
    ports:
      - "3000:3000"
    restart: "always"

  redis:
    image: "redis:alpine"
    command: sh -c "sleep 5; /usr/local/bin/redis-server"
    volumes:
      - data:/data

volumes:
  data:

