version: "3.9"

services:
  web:
    image: node:17
    working_dir: /app
    command: bash -c "npm install && node server.js"
#    command: bash -c "sleep infinity"
    volumes:
      - ".:/app"
    ports:
      - "13000:3000"
      - "13001:3001"
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: example
      MONGO_HOST: mongo
      PORT: 3001

  mongo:
    image: mongo:5
    command: bash -c "sleep 60 && /usr/local/bin/docker-entrypoint.sh mongod"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


