version: "3.9"

services:
  web:
    image: node:17
    working_dir: /app
    command: bash -c "npm install && node server.js"
    volumes:
      - ".:/app"
    depends_on:
      - mongo
    ports:
      - "13000:3000"
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: example
      MONGO_HOST: mongo

  mongo:
    image: mongo:5
#    removed sleep 60
    command: bash -c "mongod"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


